[Feature] Add implementation GRPC
ichiro-its/shisen_interfaces pull request #3
Opened 2024-04-17 04:01 UTC by mbsaloka

## Jira Link: 
https://ichiro-its.atlassian.net/browse/PD-405?atlOrigin=eyJpIjoiYjlkNDI3NGEzY2M3NDMyMzk3ZWYzYmQxZTllZjEyZDciLCJwIjoiaiJ9

## Description
Added protobuf for grpc

## Type of Change

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause the existing functionality to not work as expected)

## How Has This Been Tested?

- [ ] New unit tests added.
- [x] Manual tested.

## Checklist:

- [x] Using Branch Name Convention
    - `feature/JIRA-ID-SHORT-DESCRIPTION` if has a JIRA ticket
    - `enhancement/SHORT-DESCRIPTION` if has/has no JIRA ticket and contain enhancement
    - `hotfix/SHORT-DESCRIPTION` if the change doesn't need to be tested (urgent)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made the documentation for the corresponding changes.

2024-04-17 12:28 UTC, JayantiTA requested changes, later dismissed

2024-04-17 12:28 UTC, JayantiTA commented on .github/pull_request_template.md
don't remove this file please

2024-04-17 12:28 UTC, JayantiTA commented on .gitignore
this file doesn't need to be committed

2024-04-19 08:15 UTC, threeal requested changes

2024-04-19 08:15 UTC, threeal commented on CMakeLists.txt
> +# endif()
Why was it commented?

2024-04-19 08:15 UTC, threeal commented on CMakeLists.txt
> +# ament_export_dependencies(rosidl_default_runtime)
This too?

2024-04-19 08:15 UTC, threeal commented on CMakeLists.txt
> +      DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/proto/shisen.proto)
Can you format this better?
- Use 2 spaces like the other lines.
- Put end bracket on new line like the other lines.
- Either put argument lists aligned with the argument key or follow 2 spaces tabulation.

2024-04-20 07:49 UTC, threeal approved these changes

2024-06-05 16:40 UTC, marfanr approved these changes

2024-06-05 16:41 UTC, merged